# Generated by Django 4.1.1 on 2023-05-28 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0018_autobiographys_introductions"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="autobiographys",
            new_name="autobiography",
        ),
        migrations.RenameModel(
            old_name="introductions",
            new_name="introduction",
        ),
    ]
