# Generated by Django 4.1.1 on 2023-05-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0025_homepost_ownerid"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
